############################################################
#
# 数据源 相关信息
#
############################################################
spring:
  datasource: # 数据源相关配置
    url: jdbc:mysql://localhost:3306/food_shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  redis:
    # redis 单机单实例
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
#    # redis 哨兵模式
#    database: 1
#    password: test
#    sentinel:
#      master: redis-master # 哨兵主节点名称
#      nodes: 192.168.1.191:26379,192.168.1.192:26379,192.168.1.193:26379 # 哨兵节点ip地址
#    # redis 集群模式
#    password: test
#    cluster: # 配置集群节点ip
#      nodes: 192.168.1.201:6379,192.168.1.202:6379,192.168.1.203:6379,192.168.1.204:6379,192.168.1.205:6379,192.168.1.206:6379

